### ISSUE TITLE
Usage problems

### ISSUE THREAD

**Issue by grav** [tomclegg/mp3cat#1]
Hi! 

I'd like to merge several mp3s in a dir to one big file.
I've installed mp3cat, but I cannot seem to get it working. I'm using the following command:

```
$ mp3cat segments - > merged.mp3
```

where segments is a dir full of mp3s.

I got the example from http://tomclegg.net/mp3cat

I get the following repeating error:

```
Couldn't open segments/current.mp3 (No such file or directory), trying again
Couldn't open segments/current.mp3 (No such file or directory), trying again
...
```

I've tried touch'ing segments/current.mp3, but that just seems to hang mp3cat as if it's waiting for input.

I'm probably misunderstanding something related to piping data on unix?

**Comment by tomclegg** [comment]
Hi Mikkel,

The "mp3dir" in the examples is used as a buffer for streaming content. "mp3cat foo -" means read forever from the stream as it arrives in foo/current.mp3, and output valid frames to stdout.

I think this will do what you want:

```
cat segments/*.mp3 | mp3cat - - > merged.mp3
```

Aside: If your input files consist entirely of valid mp3 frames, you don't need mp3cat at all and this will work just as well:

```
cat segments/*.mp3 > merged.mp3
```

**Comment by grav** [comment]
Hi Tom! Thanks for the quick response.

Won't I have multiple headers if I just cat the files (as in your second example)? And won't that make some players hiccup?

**Comment by grav** [comment]
Okay, I got a bit further now. I tested both your suggestions against decoding with LAME.

The cat method in your second example - without mp3cat - outputs multiple headers, and LAME complains:

```
skipping initial 529 samples (encoder+decoder delay)
Frame#   331/1989702  96 kbps         hip: bitstream problem, resyncing skipping 357826 bytes...
Frame# 19232/1989702  96 kbps         hip: bitstream problem, resyncing skipping 357826 bytes...
Frame# 33937/1989702  96 kbps         hip: bitstream problem, resyncing skipping 357826 bytes...
Frame# 36731/1989702  96 kbps         ^C      
```

Piping it though mp3cat as in your first example works fine.

**Comment by paulcobbaut** [comment]
> Hi Mikkel,
> 
> The "mp3dir" in the examples is used as a buffer for streaming content. "mp3cat foo -" means read forever from the stream as it arrives in foo/current.mp3, and output valid frames to stdout.
> 
> I think this will do what you want:
> 
> ```
> cat segments/*.mp3 | mp3cat - - > merged.mp3
> ```
> 
> Aside: If your input files consist entirely of valid mp3 frames, you don't need mp3cat at all and this will work just as well:
> 
> ```
> cat segments/*.mp3 > merged.mp3
> ```

Seems like a useful example for the readme. (Also thanks for mp3cat!)
